### PR TITLE
Dependency update and tooling

### PR DESCRIPTION
**Pull request by rpoet-jh**
The following changes were done in this PR:

- Updated dependencies
- Added enforcer dependency convergence plugin config, runs before compile phase
- Added dependency analyze plugin config, run after test-compile phase

### CODE REVIEW

**Review by markpatton — APPROVED** [review]
This is a great cleanup. All the tests pass for me locally and things worked when I played around with them, but I noticed a few small issues, some longstanding.

In deposit-core/pom.xml that `<version>${maven-failsafe-plugin.version}</version>` should be removed.

In the main pom, dependency management is defined for a few artifacts that then have those versions overridden: logback-classic, jcl-over-slf4j, slf4j-api. Is that intended? Maybe these would be better as dependency management in the toplevel pass-core and pass-support poms if those versions can't be shared. 

Interestingly my IDE reports a few other versions being overridden, but I can't figure out by what: spring-boot-starter-mail, mockito-inline, junit-jupiter, localstack.

Very minor pom issue that has been around for a while is that the pass-support and pass-data-client poms define `<version>` when they don't need to.

**Comment by rpoet-jh** [comment]
> Interestingly my IDE reports a few other versions being overridden, but I can't figure out by what: spring-boot-starter-mail, mockito-inline, junit-jupiter, localstack.

@markpatton Thanks!  I have addressed all your points except the one above.  Which project(s) did you see the versions overridden?

**Comment by markpatton** [comment]
@rpoet-jh 

My IDE is reporting these dependencies being overridden. I'm not sure how it is making that determination.

deposit-core/pom.xml: junit-jupiter, localstack, spring-boot-starter-mail, mockito-inline, junit-jupiter, spring-integration-mail

deposit-util/pom.xml: junit-jupiter

As an experiment I removed the version tags for those dependencies and deposit services built successfully.

**Comment by rpoet-jh** [comment]
> @rpoet-jh
> 
> My IDE is reporting these dependencies being overridden. I'm not sure how it is making that determination.
> 
> deposit-core/pom.xml: junit-jupiter, localstack, spring-boot-starter-mail, mockito-inline, junit-jupiter, spring-integration-mail
> 
> deposit-util/pom.xml: junit-jupiter
> 
> As an experiment I removed the version tags for those dependencies and deposit services built successfully.

@markpatton good catch.  I figured it out, most of the versions were not needed because they are being resolved by the spring-boot-dependencies dep in pass-deposit-services pom, I removed those versions.  For the mockito-inline in deposit-core, it was because I had the version prop too low, I moved it up pass-deposit-services pom.

**Pull request merged**
